name: LLM PR Review

on:
  pull_request:
      types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
    
# These permissions are needed for the review-PR to use github_token
permissions:
  pull-requests: write
  contents: read
  
jobs:
  review-pr:
    uses: xander-rudolph/.github/.github/workflows/ollama-pr.yml@main
    secrets: inherit
    with:
      model: deepseek-coder-v2

  trivy:
    name: Trivy scan
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Run Trivy fs mode
    #   uses: aquasecurity/trivy-action@0.20.0
    #   with:
    #     scan-type: 'fs'
    #     scan-ref: '.'
    #     format: 'sarif'
    #     output: 'fs-trivy-results.sarif'
    #     ignore-unfixed: true
    #     severity: 'CRITICAL,HIGH'

    # - name: Upload Trivy fs
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: 'fs-trivy-results.sarif'
    #     category: fs-results

    - name: Run Trivy config mode
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'sarif'
        output: 'config-trivy-results.sarif'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy config
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'config-trivy-results.sarif'
        category: config-results