name: Run Pipeline

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  changes:
    uses: xander-rudolph/.github/.github/workflows/terraform-changes.yaml@insomnia
    secrets: inherit
    with:
      working_dir: modules/

  validate:
    if: ${{ needs.changes.outputs.changes != '[]' }}
    needs: changes
    strategy:
      matrix:
        module_path: ${{ fromJson(needs.changes.outputs.changes) }}
    uses: xander-rudolph/.github/.github/workflows/terraform-commit-validate.yaml@insomnia
    secrets: inherit
    with:
      working_dir: ${{ matrix.module_path }}

  repo:
    #TODO: add some sort of additional conditions here
    if: ${{ needs.changes.outputs.changes != '[]'}}
    needs: changes
    strategy:
      matrix:
        module_path: ${{ fromJson(needs.changes.outputs.changes) }}
    uses: xander-rudolph/.github/.github/workflows/terraform-repo-create.yaml@insomnia
    secrets: inherit
    with:
      working_dir: ${{ matrix.module_path }}
      template: terraform-template

  publish:
    needs: [changes,validate,repo]
    strategy:
      matrix:
        module_path: ${{ fromJson(needs.changes.outputs.changes) }}
    uses: xander-rudolph/.github/.github/workflows/terraform-publish-branch.yaml@insomnia
    secrets: inherit
    with:
      working_dir: ${{ matrix.module_path }}